-- Drop existing tables (if any)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE registration CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE courses CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE students CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create students table
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    roll_number VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(20),
    department VARCHAR2(100),
    year VARCHAR2(20),
    password VARCHAR2(100) NOT NULL
);

-- Create courses table
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    instructor VARCHAR2(100) NOT NULL,
    credits NUMBER NOT NULL
);

-- Create registration table (Junction table)
CREATE TABLE registration (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    course_id NUMBER,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE,
    CONSTRAINT unique_registration UNIQUE (student_id, course_id)
);

-- Insert sample courses
INSERT INTO courses (course_name, instructor, credits) VALUES ('Introduction to Programming', 'Dr. Smith', 3);
INSERT INTO courses (course_name, instructor, credits) VALUES ('Database Management Systems', 'Prof. Johnson', 4);
INSERT INTO courses (course_name, instructor, credits) VALUES ('Web Development', 'Mr. Davis', 3);
INSERT INTO courses (course_name, instructor, credits) VALUES ('Data Structures and Algorithms', 'Dr. Brown', 4);

COMMIT;
